nome : gerar animação

em :
  horário :
      # a cada 6 horas
    - cron : " 0 * / 6 * * * "

empregos :
  gerar :
    roda em : windows-mais recente
    tempo limite-minutos : 10
    passos :
      - usa : mateushenriquefonsecaxavierdasilva
        id : snake-gif
        com :
    github_user_name :mateushenriquefonsecaxavierdasilva  
          svg_out_path : dist / snk_gif.svg

      - usa : crazy-max/ghaction-github-pages@v2.1.3
        com :
          target_branch : output
          build_dir : dist
        env :
          GITHUB_TOKEN : $ {{secrets.MY_GITHUB_TOKEN_GH_PAGES}} 
